version: '3.1'

volumes:
  postgres:

services:
  db:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
